# k8s/backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
  namespace: nest
  labels:
    app: nest-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
      containers:
      - name: backend
        image: arkid15r/owasp-nest-backend:production
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        command: ["/home/owasp/init-backend.sh", "/home/owasp/entrypoint.sh"]
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        readinessProbe:
          httpGet:
            path: /api/v1/
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 10
        # livenessProbe:
        #   httpGet:
        #     path: /api/v1/
        #     port: 8000
        #   initialDelaySeconds: 30
        #   periodSeconds: 20
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
