# k8s/backend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nest-backend
  namespace: nest
  labels:
    app: nest-backend
spec:
  selector:
    app: nest-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
