# k8s/database/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nest-db
  namespace: nest
  labels:
    app: nest-db
spec:
  selector:
    app: nest-db
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres
  type: ClusterIP
