apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nest-production-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: none
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
