# k8s/secrets/db-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_DB: bmVzdF9kYl9wcm9kdWN0aW9u  # nest_db_production
  POSTGRES_USER: bmVzdF91c2VyX3Byb2R1Y3Rpb24=  # nest_user_production
  POSTGRES_PASSWORD: bmVzdF91c2VyX3Byb2R1Y3Rpb25fcGFzc3dvcmQ=  # nest_user_production_password
