apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: nest
data:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_CONFIGURATION: "Local"
  DJANGO_DB_HOST: "nest-db"
  DJANGO_DB_NAME: "nest"
  DJANGO_DB_PORT: "5432"
  DJANGO_DB_USER: "postgres"
  DJANGO_ALGOLIA_APPLICATION_REGION: "us"
  DJANGO_ALGOLIA_EXCLUDED_LOCAL_INDEX_NAMES: "None"
  DJANGO_RELEASE_VERSION: "None"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: nest
data:
  # Vite environment variables (prefixed with VITE_) are embedded during build time, not runtime.
  VITE_API_URL: "http://nest.backend/api/v1"
  VITE_GRAPHQL_URL: "http://nest.backend/graphql/"
  VITE_IDX_URL: "http://nest.backend/idx/"
  VITE_ENVIRONMENT: "local"
  VITE_GTM_AUTH: "your-google-tag-manager-auth"
  VITE_GTM_ID: "your-google-tag-manager-id"
  VITE_GTM_PREVIEW: 
  VITE_RELEASE_VERSION: 
  VITE_SENTRY_DSN: 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: nest
data:
  POSTGRES_DB: "nest"
  POSTGRES_USER: "postgres"
