apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nest-ingress
  namespace: nest
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: nest.frontend
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nest-frontend
            port:
              number: 3000
  - host: nest.backend
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nest-backend
            port:
              number: 8000
