apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nest-backend-hpa
  namespace: nest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nest-backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nest-frontend-hpa
  namespace: nest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nest-frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nest-db-hpa
  namespace: nest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: nest-db
  minReplicas: 1
  maxReplicas: 2  # Lower max for database as scaling DB horizontally requires more care
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300  # More conservative scale-up for database
    scaleDown:
      stabilizationWindowSeconds: 600  # More conservative scale-down for database
