apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
  namespace: nest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      containers:
      - name: backend
        image: nest-backend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        command: ["/bin/bash", "-c"]
        args:
        - |
          echo "Waiting for database to be ready..."
          until python -c "import socket; socket.socket().connect(('nest-db', 5432))" 2>/dev/null; do
            echo "Database not ready yet. Waiting..."
            sleep 2
          done
          echo "Database is ready. Setting up Django environment..."
          python manage.py migrate
          echo "Starting server..."
          python manage.py runserver 0.0.0.0:8000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        volumeMounts:
        - mountPath: /home/owasp
          name: backend-volume
        - mountPath: /home/owasp/.venv
          name: backend-venv
      volumes:
      - name: backend-volume
        hostPath:
          path: /home/adii/Desktop/GSoC2025/Nest/backend
          type: Directory
      - name: backend-venv
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nest-backend
  namespace: nest
spec:
  selector:
    app: nest-backend
  ports:
  - port: 8000
    targetPort: 8000
