apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-frontend
  namespace: nest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-frontend
  template:
    metadata:
      labels:
        app: nest-frontend
    spec:
      containers:
      - name: frontend
        image: nest-frontend:local
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        command: ["/bin/bash", "-c"]
        args: ["pnpm install && pnpm run dev"]
        envFrom:
        - configMapRef:
            name: frontend-config
        volumeMounts:
          - mountPath: /home/owasp
            name: frontend-volume
      volumes:
      - name: frontend-volume
        hostPath:
          path: /home/adii/Desktop/GSoC2025/Nest/frontend
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: nest-frontend
  namespace: nest
spec:
  selector:
    app: nest-frontend
  ports:
  - port: 3000
    targetPort: 3000
