apiVersion: v1
kind: Namespace
metadata:
  name: nest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: nest
data:
  DJANGO_CONFIGURATION: "Local"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_DB_HOST: "nest-db"
  DJANGO_DB_NAME: "nest_db_dev"
  DJANGO_DB_USER: "nest_user_dev"
  DJANGO_DB_PORT: "5432"
  DJANGO_ALGOLIA_APPLICATION_REGION: "us"
  DJANGO_ALGOLIA_EXCLUDED_LOCAL_INDEX_NAMES: "None"
  DJANGO_DEBUG: "True"
  DJANGO_SETTINGS_MODULE: "config.settings"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: nest
data:
  NODE_ENV: "local"
  VITE_API_URL: "http://nest.local/api/v1/"
  VITE_ENVIRONMENT: "local"
  VITE_GRAPHQL_URL: "http://nest.local/graphql/"
  VITE_IDX_URL: "http://nest.local/idx/"
  VITE_GTM_AUTH: "your-google-tag-manager-auth"
  VITE_GTM_ID: "your-google-tag-manager-id"
  VITE_GTM_PREVIEW: ""
  VITE_RELEASE_VERSION: ""
  VITE_SENTRY_DSN: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: nest
type: Opaque
data:
  DJANGO_SECRET_KEY: "eW91ci1zZWNyZXQta2V5"
  DJANGO_DB_PASSWORD: "bmVzdF91c2VyX2Rldl9wYXNzd29yZA=="
  DJANGO_ALGOLIA_APPLICATION_ID: "REFSVFA3TllFMw=="
  DJANGO_ALGOLIA_WRITE_API_KEY: "NTk5MTRhNDA4MTdhZGMwMjQ1MWE3MDdhOTc2ZTk1MmY="
