apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: nest
data:
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_CONFIGURATION: "Local"
  DJANGO_DB_HOST: "nest-db"
  DJANGO_DB_NAME: "nest_db_dev"
  DJANGO_DB_PORT: "5432"
  DJANGO_DB_USER: "nest_user_dev"
  # Note: Secrets like API keys should be in a Secret, not ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: nest
data:
  VITE_API_URL: "http://nest-backend:8000/api/v1/"
  VITE_ENVIRONMENT: "local"
  VITE_GRAPHQL_URL: "http://nest-backend:8000/graphql/"
  VITE_IDX_URL: "http://nest-backend:8000/idx/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: nest
data:
  POSTGRES_DB: "nest_db_dev"
  POSTGRES_USER: "nest_user_dev"
