# k8s/frontend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nest-frontend
  labels:
    app: nest-frontend
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: nest-frontend
